services:
  elasticsearch:
    image: elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - ES-JAVA_OPTS="-XX:UseSVE=0"
      - xpack.security.enabled=false
    ports:
      - '127.0.0.1:9200:9200'
  capture:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    command: /opt/arkime/bin/docker.sh capture --update-geo -m -R /opt/arkime/raw -n node00
    environment:
      - ARKIME__elasticsearch=elasticsearch:9200
    volumes:
      - ./arkime/etc/:/opt/arkime/etc/
      - ./raw:/opt/arkime/raw
    restart: always
  viewer:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    command: /opt/arkime/etc/start.sh
    environment:
      - ARKIME__elasticsearch=http://elasticsearch:9200
    volumes:
      - ./arkime/etc/:/opt/arkime/etc/
      - ./raw:/opt/arkime/raw
    restart: always
    ports:
      - '127.0.0.1:8005:8005'
