services:
  elasticsearch:
    image: elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - ES-JAVA_OPTS="-XX:UseSVE=0"
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=10s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  capture:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    command: /opt/arkime/bin/docker.sh capture --update-geo -m -R /opt/arkime/raw -n node00
    environment:
      - ARKIME__elasticsearch=elasticsearch:9200
    volumes:
      - ./arkime/etc/:/opt/arkime/etc/
      - ./raw:/opt/arkime/raw
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
      viewer:
        condition: service_healthy
  viewer:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    command: /opt/arkime/etc/start.sh
    environment:
      - ARKIME__elasticsearch=http://elasticsearch:9200
    volumes:
      - ./arkime/etc/:/opt/arkime/etc/
      - ./raw:/opt/arkime/raw
    restart: always
    ports:
      - '127.0.0.1:8005:8005'
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "test -f /initialized"]
      interval: 5s         # Check every 5 seconds
      timeout: 3s          # Wait up to 3 seconds for the command to complete
      retries: 10          # Try 10 times before marking as unhealthy
      start_period: 5s
